# Development Configuration
# Environment variables can override any setting using ${VAR_NAME:default_value} syntax

# Server settings
host: "${HOST:0.0.0.0}"
port: "${PORT:8000}"
debug: true

# API settings
title: "Role Play System - Development"
description: "Role Play System API - Development Environment"
version: "1.0.0-dev"

# CORS settings
enable_cors: true
cors_origins:
  - "http://localhost:3000"
  - "http://localhost:5173"
  - "http://localhost:8080"
  - "${CORS_ORIGIN:}"  # Optional additional CORS origin via env var

# Authentication settings
jwt_secret_key: "${JWT_SECRET_KEY:development-secret-key}"
jwt_algorithm: "HS256"
jwt_expire_hours: "${JWT_EXPIRE_HOURS:24}"

# Storage settings (new configurable format)
# To use GCS in dev: STORAGE_TYPE=gcs GCS_BUCKET=your-bucket GCS_PREFIX=dev/
storage:
  type: "${STORAGE_TYPE:file}"
  # File storage settings
  base_dir: "${STORAGE_PATH:./data}"
  # GCS storage settings (only used if type is 'gcs')
  bucket: "${GCS_BUCKET:}"
  prefix: "${GCS_PREFIX:dev/}"
  project_id: "${GCP_PROJECT_ID:}"
  credentials_file: "${GCP_CREDENTIALS_FILE:}"
  # S3 storage settings (only used if type is 's3')
  s3_bucket: "${S3_BUCKET:}"
  s3_prefix: "${S3_PREFIX:dev/}"
  aws_region: "${AWS_REGION:us-east-1}"
  aws_access_key_id: "${AWS_ACCESS_KEY_ID:}"
  aws_secret_access_key: "${AWS_SECRET_ACCESS_KEY:}"
  # Lock configuration
  lock:
    strategy: "${LOCK_STRATEGY:file}"
    lease_duration_seconds: "${LOCK_LEASE_DURATION:60}"
    retry_attempts: "${LOCK_RETRY_ATTEMPTS:3}"
    retry_delay_seconds: "${LOCK_RETRY_DELAY:1.0}"
    # Redis settings (only used if strategy is 'redis')
    redis_host: "${REDIS_HOST:}"
    redis_port: "${REDIS_PORT:6379}"
    redis_password: "${REDIS_PASSWORD:}"
    redis_db: "${REDIS_DB:0}"

# Legacy storage settings (maintained for backward compatibility)
storage_type: "file"
storage_path: "${STORAGE_PATH:./data}"

# Handler configuration - map handler names to their import paths
enabled_handlers:
  user_account: "role_play.server.user_account_handler.UserAccountHandler"
  chat: "role_play.chat.handler.ChatHandler"
  evaluation: "role_play.evaluation.handler.EvaluationHandler"
  # Add more handlers as they're implemented:
  # scripter: "role_play.scripter.handler.ScripterHandler"

# Language configuration
supported_languages:
  - "en"
  - "zh-TW"
  - "ja"