name: Python Unit Tests

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('src/python/requirements-all.txt', 'src/python/requirements.txt', 'src/python/requirements-test.txt', 'src/python/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/python/requirements-all.txt

      - name: Run unit tests
        env:
          ENV: dev
          PYTHONUNBUFFERED: '1'
        run: |
          python -m pytest test/python/unit/ -q
